# Generated by Django 3.1.6 on 2021-04-15 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('stockPrice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('ftwh', models.DecimalField(decimal_places=2, max_digits=7)),
                ('ftwl', models.DecimalField(decimal_places=2, max_digits=7)),
                ('dateAdded', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='portEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharesOwned', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyticals.stock')),
            ],
        ),
    ]
