# Generated by Django 3.2.3 on 2021-06-01 00:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analyticals', '0002_auto_20210419_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='dateAdded',
        ),
        migrations.AddField(
            model_name='stock',
            name='companyDescrip',
            field=models.CharField(default=django.utils.timezone.now, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='companyName',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
