# Generated by Django 3.2.3 on 2021-06-01 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticals', '0003_auto_20210531_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='companyDescrip',
            field=models.CharField(max_length=100000),
        ),
    ]
